
import { User, VirtualCard, PhysicalCard, Trip, Transaction, LoyaltyEvent, Provider, CardTheme, RouteOption, Challenge, Reward, TransitAlert } from './types';

// Add missing role property to satisfy User interface
export const DEMO_USER: User = {
  id: 'user-1',
  fullName: 'Sizwe Ndlovu',
  email: 'sizwe@example.com',
  loyaltyPoints: 1250,
  pin: '1234',
  role: 'commuter',
};

export const DEMO_VIRTUAL_CARD: VirtualCard = {
  cardNumber: '5018 1234 5678 9101',
  cardHolderName: 'Sizwe Ndlovu',
  validThru: '12/28',
  balance: 157.50,
  theme: 'mzansi',
};

export const DEMO_PHYSICAL_CARDS: PhysicalCard[] = [
  { id: 'pc-1', provider: 'Rea Vaya', cardNumber: '**** 4567', nickname: 'Work Rea Vaya', balance: 120.50 },
  { id: 'pc-2', provider: 'Gautrain', cardNumber: '**** 8901', nickname: 'Gautrain Card', balance: 350.00 },
];

// Add missing timestamp property to satisfy Trip interface
export const DEMO_TRIPS: Trip[] = [
  { id: 'trip-1', provider: 'Gautrain', from: 'Sandton', to: 'Hatfield', date: '2024-07-20', fare: 85.00, timestamp: '2024-07-20T10:00:00Z' },
  { id: 'trip-2', provider: 'Rea Vaya', from: 'Ellis Park', to: 'Soweto', date: '2024-07-19', fare: 25.50, timestamp: '2024-07-19T08:30:00Z' },
  { id: 'trip-3', provider: 'Metrobus', from: 'Randburg', to: 'Braamfontein', date: '2024-07-18', fare: 18.00, timestamp: '2024-07-18T17:45:00Z' },
];

export const DEMO_TRANSACTIONS: Transaction[] = [
  { id: 'txn-1', date: '2024-07-15', amount: 200.00, status: 'Completed' },
  { id: 'txn-2', date: '2024-07-01', amount: 150.00, status: 'Completed' },
];

export const DEMO_LOYALTY_EVENTS: LoyaltyEvent[] = [
    { id: 'le-1', type: 'trip', description: 'Trip from Sandton', date: '2024-07-20', points: 85 },
    { id: 'le-2', type: 'top-up', description: 'Top-up R200.00', date: '2024-07-15', points: 20 },
    { id: 'le-3', type: 'bonus', description: 'Monthly Bonus', date: '2024-07-01', points: 100 },
];

export const CARD_THEMES: Record<CardTheme, string> = {
    mzansi: 'from-yellow-400 via-black to-green-600',
    ocean: 'from-blue-500 to-cyan-400',
    forest: 'from-green-600 to-emerald-800',
    sunset: 'from-orange-500 via-red-500 to-purple-600',
    charcoal: 'from-gray-800 to-gray-900',
};

export const PROVIDER_COLORS: Record<Provider, string> = {
    'Rea Vaya': 'bg-red-500 text-white',
    'Metrobus': 'bg-yellow-400 text-black',
    'Gautrain': 'bg-blue-600 text-white',
    'MyCiTi': 'bg-cyan-500 text-white',
    'Areyeng': 'bg-green-500 text-white',
    'Tshwane Bus Service': 'bg-teal-500 text-white',
    'PRASA': 'bg-purple-600 text-white',
};

export const PROVIDER_PREFIXES: Record<string, Provider> = {
  'RV': 'Rea Vaya',
  'GT': 'Gautrain',
  'MB': 'Metrobus',
  'MC': 'MyCiTi',
  'AY': 'Areyeng',
  'PR': 'PRASA',
  'TB': 'Tshwane Bus Service',
};

export const STATIONS: Record<Provider, string[]> = {
    'Rea Vaya': ['Ellis Park', 'Soweto Theatre', 'Thokoza Park', 'Library Gardens', 'Art Gallery'],
    'Metrobus': ['Randburg CBD', 'Sandton City', 'Rosebank', 'Braamfontein', 'Gandhi Square'],
    'Gautrain': ['Park Station', 'Rosebank', 'Sandton', 'Marlboro', 'Midrand', 'Centurion', 'Pretoria', 'Hatfield', 'OR Tambo'],
    'MyCiTi': ['Civic Centre', 'Table View', 'Century City', 'V&A Waterfront', 'Gardens'],
    'Areyeng': ['Church Square', 'Sunnyside', 'Menlyn', 'Hatfield', 'Wonderboom'],
    'Tshwane Bus Service': ['Pretoria CBD', 'Brooklyn', 'Lynnwood', 'Garsfontein', 'Montana'],
    'PRASA': ['Park Station', 'Germiston', 'Pretoria', 'Soweto', 'Tembisa', 'Mamelodi'],
};

export const MOCK_TRIP_PLAN: RouteOption[] = [
    {
        title: "Balanced Route",
        tag: "Recommended",
        totalFare: 45.50,
        travelTime: "55 min",
        steps: [
            { provider: "Rea Vaya", from: "Sandton", to: "Rosebank", instruction: "Take the T3 bus towards Park Station." },
            { provider: "Gautrain", from: "Rosebank", to: "Park Station", instruction: "Switch to the Gautrain South-bound train." },
        ]
    },
    {
        title: "Cheapest Option",
        tag: "Cheapest",
        totalFare: 22.00,
        travelTime: "1 hr 15 min",
        steps: [
            { provider: "Metrobus", from: "Sandton", to: "Gandhi Square", instruction: "Take route 5A directly to the city center." },
            { provider: "Metrobus", from: "Gandhi Square", to: "Park Station", instruction: "Short walk or connecting bus route 2C." },
        ]
    }
];

export const DEMO_CHALLENGES: Challenge[] = [
    { id: 'ch-1', title: 'First Five', description: 'Take your first 5 trips to earn a big bonus.', points: 250, goal: 5, type: 'trip_count' },
    { id: 'ch-2', title: 'Weekly Rider', description: 'Complete 10 trips in a single week.', points: 150, goal: 10, type: 'trip_count' },
    { id: 'ch-3', title: 'Top-up Pro', description: 'Top up a total of R500 across all your cards.', points: 100, goal: 500, type: 'top_up_amount' },
];

export const DEMO_REWARDS: Reward[] = [
    { id: 'rw-1', title: 'R10 Top-up Voucher', description: 'Get R10 added to your virtual card balance.', cost: 500, type: 'top_up_voucher', value: 10 },
    { id: 'rw-2', title: 'R25 Top-up Voucher', description: 'Get R25 added to your virtual card balance.', cost: 1100, type: 'top_up_voucher', value: 25 },
    { id: 'rw-3', title: 'R50 Top-up Voucher', description: 'Get R50 added to your virtual card balance.', cost: 2000, type: 'top_up_voucher', value: 50 },
];

export const DEMO_TRANSIT_ALERTS: TransitAlert[] = [
  {
    id: 'alert-1',
    type: 'official',
    provider: 'Gautrain',
    category: 'delay',
    title: 'Major Delays on North-South Line',
    description: 'Due to a technical issue at Sandton station, expect major delays of up to 45 minutes on the North-South line between Park Station and Hatfield.',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
  },
  {
    id: 'alert-2',
    type: 'user_report',
    provider: 'Rea Vaya',
    category: 'crowded',
    title: 'T1 Bus Extremely Crowded',
    description: 'The T1 bus leaving Ellis Park is packed. Might be better to wait for the next one if you can.',
    timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 mins ago
  },
  {
    id: 'alert-3',
    type: 'user_report',
    provider: 'Metrobus',
    category: 'info',
    title: 'Ticket inspectors on route 5A',
    description: 'Just a heads-up, inspectors are checking tickets on the bus from Randburg.',
    timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(), // 35 mins ago
  },
];

export const DEMO_LANDMARKS = [
  {
    name: "Union Buildings",
    base64: "/9j/4AAQSkZJRgABAQEASABIAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIbGNtcwIQAABtbnRyUkdCIFhZWiAH4gADABQACQAOAB1hY3NwTVNGVAAAAABzYXdzY3RybAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWhhbmRhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARUFNBwAAAAECAAAAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAYAAAAOAAAAaGVkcwAAAAsAAAAYaGVkc2NsbXMAAAABAAAAAmhlZHNtbG8AAAABAAAACHVzYmAAAAAJAAAAIHRleHQAAAAAQ29weXJpZ2h0IChjKSAyMDAwLCAyMDAxIFNhcmdlbnQgVGVjaG5vbG9naWVzLCBJbmMuIEFsbCByaWdodHMgcmVzZXJ2ZWQuAEhZWiAAAAAAAAD21gABAAAAANMtWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYqAAAMs0AAAK2VhZWiAAAAAAAAAknwAAD4QAALbEY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKMAqACtALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAicCOAJBAksCVAJdAmcCcQJ6Ao4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gL/Al8CngK+At8DvwPYA/8EYQTMBQAF3AYIBoYHFgddB4QH/wgRCCsJOAqADrQP7BAAENgRZBKQEyQXpBjsGeQPpB44H6AgWCDQIZgiWCQ4Jdgn4CgQKQApkCqgLBAu8DBgM+A0ADUgNYA2YDdQPGB/wIKgg/COQJFgl4CbgKBAqgCwwL+gzADCgM8A1sDcgOKBDsFNAY8BlIGuAb8ByAHYAfQCBwIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8BzAHYAfQCBAIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8B0AHRwf1B/gIEQgrCUsJtQnACeoLBAuIC/wMGAx4DUANzBAAENgRpBKwEyQXYBoYHBgdvB8QIFQgfCMEJMgm4CiwKqgucDDoMogzaDXoN7g4YDhQOew6VDuQPkA/gEBQQkBHEEpATgBPcFRAVixYEFnAXcBf4GEwYrBmAGeAaMBqgG+wcUBxQHYgekB9wIBggYCFgIXgiACIgI0AkcCWgJvAnMCewKQAqMCswLMAtgC5AL0AwADBgMIAw4DRAMuA0ADUgNWA2cDcgN8A4YDlgOiA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBDkETwRiBHYEkwTTBPAFCwVKBVwFdwWGBeAGHwYlBjsGRgZVBmQGcgahBqoGtgblBwQHJAczB08HggeyB9oICghFCHoI3AkUCUgJXgmgCbgJ8AocCjgKWgqECrgLDguRC8AMOAybDOwNUA1kDbAN7A4SDkgOXw6gDswPcBAGEEwQhBH4ElATaBUEFeoWUBcAGHAYrBmUGeQamBrcG9AdEB5YHxAgOCDoIigjMCPgJcgmcCggKlgrWDB4MWQzNDPgNUA10DbwN+A4iDmIOpA8gD4gQBBBoEXASNBOME/wVBBX4FvAYyBnYGvgc4B4QH3wgFCHoI2QklCWAJogomCpwK4gxQDHgM3A0UDWwNsA3oDiQOag6gDygPuhAIEQwRJBKQE5QV/Ba4GMwZ5Br8HOAeEB98IBQiECM0JHAloCbIKJAqbCuIMUAx4DNwNFQ1sDbAN6A4kDmoOoA8oD7oQCBEMEiQSkBOYFfwWuBjMGeQa/BzgHhAffCAUIhAjNCSEMhA2KDZIOjA+mEFgQ4BGYE6gUOBTYFZgWuBdoF/AYiBjkGYwZ6BqAGqwarBrkGvgbCBuoG9gcDBw8HJwdHB4MHkgelB8YH3Af8CAQIEgg2CDgIQQhHCHoIgwiRCLAI0gjvCToJVAlaCWQJbwmyCcwJ2wn0CgMKFAoqCjoKWgqbCqgKsgq6CsYK8gsGDCIMYgyKDMQNBA0wDUUNYA12DggOJA5QDmYOcw6dDswPChAYEEwQcBDwEYARuBIsExwT2BRQFQwVXBXoFgQWYBbwGAwYRBiEGNQZIBlQGbAadBqoGvgbCBvQHDQcZBz4HRAdXB5kHpQfZCBkIYAhtCJgI6QkMCToJaAmACZwKKApyCqIK1gt6DGAMcw04DWwN0g40DowOvw9jEIgQ4hLyE/gVDhYGFwoXThfaGAcYfBnzGo8bHBveHAYcCx1kHpcfzCAaIYsi0iQuJl0ngigNKQ0q5iwyLrsvbDAqMTwxvDPcNVA1xDcgOBQ5gDpsO6Q8RDycPSw+SD+EQChCRES0RrhK+Ey4TvhREFLgVuhYEFsoXbBgAGLwZsBoMGnQbYhyCHLwdZx5+HwQfziAGIP4hxiLYJDAmSCdIKKopZiuCLcAvYDA0MWAx4DIIMoQysjOKM+Q0NDToNf43JDkMOe47PDy8PoJAQkMCRkJMAlBCVMJcgmLiaEKggrSCwULlQvqDAcMGwxuDJ0M5g0cDWQNxQ4QDjUOhw7MDxsPNQ+MEBcQbhC8EdASVBOmFFgVaheSGN4Z2hqEGyQcRB1aHscgIiH4IqQleCakKLQqTCwoLjQwaDHIM1g3ADgQOdA7KDwMPVRAhEJwRvBL4E9AUyBXIFrwYdBnsGrAcAh1yHwQhSiNoJgAq6Cz4MBAyWDY0ON5AEkHcSd5N2E9gVDRZQF2QYEBl/GjYbMBx7HcEflCDiI7Yl8Ch2KsYvgDTwN6NAf0RzSg9PV1DkViNYPFlOWvJeyWOOZu9nlGkEaqxu9nMMc6x4XHv4g2yHcIu8m0yhOKoMtNzCsNlM55DzCP0tA6kQSRdJMcE5xUHhWj1v0YfJniGsoby9zOHRMewp/CIUojDCSiJaMo3CtVLvQzhDPsNeE6bDxQP2JCykU2Sm5MUU8lV8lfyWMJpVo4mmdb4Nz9HXte9yDSItMl5ic86IUp/iuMLJgssy4w8C0y8vVztXe4N/04vLnw+n07gQJBaQGFwc7B8UIMQl6CcsKrAu4DHkNCA4iDvsQiRKEFDsWOhpIHLkfxyMeJ4sozSvmMP81CDcuOoE/UUIiR/ZNJVFSV0pdn2QeaWptL3IidwF764FihS2LVJNRm4yjxavbtfG+68kIzU7X+eM76z/zBv9LBCcHdQfDCFIJewn/CykL2gy/DTsOaA+QEMkS1hTqFo8Z3hpwG30cxh2fHvofSiEyIn4jfSQrJicn4yisKiwrLCu8LDAscCzAprovyDA7MWoyZzNVM5g0LDVgNfQ29Df0ODo5vjrQOz883D2aPno/ZkBoQSJCfENiRCpFWkapS2tNWk9eULBSnlWIVp1XjFg0WhBbaF7wYjBkUGeYaNhrKHCgc7R3eHr8g+CKOJcMnaCjUq8YxLzXSOiQ/N0EnQf/CDwJMAp9C1MMtg1ZDfgOzA/zEVYVFRcwGSEbHB22H8MifiYHKQUs7DG2Ndg75kFASf1Mv1T4V+tlP2qxdHl8oIAYtPm+Gkj7f9vfr/sQI1BbMHNAfwCJMJ4Ar2C+sM2g15Dh0P1BE6E6oVWxesGaAbHBzMHeIfoiI8JLsmMylGKcIs0jEyNTM4dD8oRwNN/lYqXyRpoXY4geiXj6QJt+7b9e/c8ePy5frH/fUE+wdOCFwI/Qk3CqAL7gyhDW0OAQ+0ESIT4BWhF64ZlBrgG5Ic+B6iH7chxCOqJPwpwS3+MXo32D2kSNRR1lqUX25o9nSsfKW8rMIAzQzT09/h6c/z+/68BJ4HEwj7CVkKeAuCDKQNRA6SD+MQvBP7FV0XUBp2HMkfhSNqKHksfDCXN3A9/UW4UmBbJWOdZfRn2WqKb/N0wHrXgv+LSpBOlkym8LzRxsrJ0s3T0tbb3uDf4uPp7PP09/n7/P/+AQMEBQYICQoLCg0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/w==",
  },
  {
    name: "Table Mountain",
    base64: "/9j/4AAQSkZJRgABAQEASABIAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIbGNtcwIQAABtbnRyUkdCIFhZWiAH4gADABQACQAOAB1hY3NwTVNGVAAAAABzYXdzY3RybAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWhhbmRhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARUFNBwAAAAECAAAAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAYAAAAOAAAAaGVkcwAAAAsAAAAYaGVkc2NsbXMAAAABAAAAAmhlZHNtbG8AAAABAAAACHVzYmAAAAAJAAAAIHRleHQAAAAAQ29weXJpZ2h0IChjKSAyMDAwLCAyMDAxIFNhcmdlbnQgVGVjaG5vbG9naWVzLCBJbmMuIEFsbCByaWdodHMgcmVzZXJ2ZWQuAEhZWiAAAAAAAAD21gABAAAAANMtWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYqAAAMs0AAAK2VhZWiAAAAAAAAAknwAAD4QAALbEY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKMAqACtALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAicCOAJBAksCVAJdAmcCcQJ6Ao4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gL/Al8CngK+At8DvwPYA/8EYQTMBQAF3AYIBoYHFgddB4QH/wgRCCsJOAqADrQP7BAAENgRZBKQEyQXpBjsGeQPpB44H6AgWCDQIZgiWCQ4Jdgn4CgQKQApkCqgLBAu8DBgM+A0ADUgNYA2YDdQPGB/wIKgg/COQJFgl4CbgKBAqgCwwL+gzADCgM8A1sDcgOKBDsFNAY8BlIGuAb8ByAHYAfQCBwIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8BzAHYAfQCBAIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8B0AHRwf1B/gIEQgrCUsJtQnACeoLBAuIC/wMGAx4DUANzBAAENgRpBKwEyQXYBoYHBgdvB8QIFQgfCMEJMgm4CiwKqgucDDoMogzaDXoN7g4YDhQOew6VDuQPkA/gEBQQkBHEEpATgBPcFRAVixYEFnAXcBf4GEwYrBmAGeAaMBqgG+wcUBxQHYgekB9wIBggYCFgIXgiACIgI0AkcCWgJvAnMCewKQAqMCswLMAtgC5AL0AwADBgMIAw4DRAMuA0ADUgNWA2cDcgN8A4YDlgOiA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBDkETwRiBHYEkwTTBPAFCwVKBVwFdwWGBeAGHwYlBjsGRgZVBmQGcgahBqoGtgblBwQHJAczB08HggeyB9oICghFCHoI3AkUCUgJXgmgCbgJ8AocCjgKWgqECrgLDguRC8AMOAybDOwNUA1kDbAN7A4SDkgOXw6gDswPcBAGEEwQhBH4ElATaBUEFeoWUBcAGHAYrBmUGeQamBrcG9AdEB5YHxAgOCDoIigjMCPgJcgmcCggKlgrWDB4MWQzNDPgNUA10DbwN+A4iDmIOpA8gD4gQBBBoEXASNBOME/wVBBX4FvAYyBnYGvgc4B4QH3wgFCHoI2QklCWAJogomCpwK4gxQDHgM3A0UDWwNsA3oDiQOag6gDygPuhAIEQwRJBKQE5QV/Ba4GMwZ5Br8HOAeEB98IBQiECM0JHAloCbIKJAqbCuIMUAx4DNwNFQ1sDbAN6A4kDmoOoA8oD7oQCBEMEiQSkBOYFfwWuBjMGeQa/BzgHhAffCAUIhAjNCSEMhA2KDZIOjA+mEFgQ4BGYE6gUOBTYFZgWuBdoF/AYiBjkGYwZ6BqAGqwarBrkGvgbCBuoG9gcDBw8HJwdHB4MHkgelB8YH3Af8CAQIEgg2CDgIQQhHCHoIgwiRCLAI0gjvCToJVAlaCWQJbwmyCcwJ2wn0CgMKFAoqCjoKWgqbCqgKsgq6CsYK8gsGDCIMYgyKDMQNBA0wDUUNYA12DggOJA5QDmYOcw6dDswPChAYEEwQcBDwEYARuBIsExwT2BRQFQwVXBXoFgQWYBbwGAwYRBiEGNQZIBlQGbAadBqoGvgbCBvQHDQcZBz4HRAdXB5kHpQfZCBkIYAhtCJgI6QkMCToJaAmACZwKKApyCqIK1gt6DGAMcw04DWwN0g40DowOvw9jEIgQ4hLyE/gVDhYGFwoXThfaGAcYfBnzGo8bHBveHAYcCx1kHpcfzCAaIYsi0iQuJl0ngigNKQ0q5iwyLrsvbDAqMTwxvDPcNVA1xDcgOBQ5gDpsO6Q8RDycPSw+SD+EQChCRES0RrhK+Ey4TvhREFLgVuhYEFsoXbBgAGLwZsBoMGnQbYhyCHLwdZx5+HwQfziAGIP4hxiLYJDAmSCdIKKopZiuCLcAvYDA0MWAx4DIIMoQysjOKM+Q0NDToNf43JDkMOe47PDy8PoJAQkMCRkJMAlBCVMJcgmLiaEKggrSCwULlQvqDAcMGwxuDJ0M5g0cDWQNxQ4QDjUOhw7MDxsPNQ+MEBcQbhC8EdASVBOmFFgVaheSGN4Z2hqEGyQcRB1aHscgIiH4IqQleCakKLQqTCwoLjQwaDHIM1g3ADgQOdA7KDwMPVRAhEJwRvBL4E9AUyBXIFrwYdBnsGrAcAh1yHwQhSiNoJgAq6Cz4MBAyWDY0ON5AEkHcSd5N2E9gVDRZQF2QYEBl/GjYbMBx7HcEflCDiI7Yl8Ch2KsYvgDTwN6NAf0RzSg9PV1DkViNYPFlOWvJeyWOOZu9nlGkEaqxu9nMMc6x4XHv4g2yHcIu8m0yhOKoMtNzCsNlM55DzCP0tA6kQSRdJMcE5xUHhWj1v0YfJniGsoby9zOHRMewp/CIUojDCSiJaMo3CtVLvQzhDPsNeE6bDxQP2JCykU2Sm5MUU8lV8lfyWMJpVo4mmdb4Nz9HXte9yDSItMl5ic86IUp/iuMLJgssy4w8C0y8vVztXe4N/04vLnw+n07gQJBaQGFwc7B8UIMQl6CcsKrAu4DHkNCA4iDvsQiRKEFDsWOhpIHLkfxyMeJ4sozSvmMP81CDcuOoE/UUIiR/ZNJVFSV0pdn2QeaWptL3IidwF764FihS2LVJNRm4yjxavbtfG+68kIzU7X+eM76z/zBv9LBCcHdQfDCFIJewn/CykL2gy/DTsOaA+QEMkS1hTqFo8Z3hpwG30cxh2fHvofSiEyIn4jfSQrJicn4yisKiwrLCu8LDAscCzAprovyDA7MWoyZzNVM5g0LDVgNfQ29Df0ODo5vjrQOz883D2aPno/ZkBoQSJCfENiRCpFWkapS2tNWk9eULBSnlWIVp1XjFg0WhBbaF7wYjBkUGeYaNhrKHCgc7R3eHr8g+CKOJcMnaCjUq8YxLzXSOiQ/N0EnQf/CDwJMAp9C1MMtg1ZDfgOzA/zEVYVFRcwGSEbHB22H8MifiYHKQUs7DG2Ndg75kFASf1Mv1T4V+tlP2qxdHl8oIAYtPm+Gkj7f9vfr/sQI1BbMHNAfwCJMJ4Ar2C+sM2g15Dh0P1BE6E6oVWxesGaAbHBzMHeIfoiI8JLsmMylGKcIs0jEyNTM4dD8oRwNN/lYqXyRpoXY4geiXj6QJt+7b9e/c8ePy5frH/fUE+wdOCFwI/Qk3CqAL7gyhDW0OAQ+0ESIT4BWhF64ZlBrgG5Ic+B6iH7chxCOqJPwpwS3+MXo32D2kSNRR1lqUX25o9nSsfKW8rMIAzQzT09/h6c/z+/68BJ4HEwj7CVkKeAuCDKQNRA6SD+MQvBP7FV0XUBp2HMkfhSNqKHksfDCXN3A9/UW4UmBbJWOdZfRn2WqKb/N0wHrXgv+LSpBOlkym8LzRxsrJ0s3T0tbb3uDf4uPp7PP09/n7/P/+AQMEBQYICQoLCg0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/w==",
  },
  {
    name: "Nelson Mandela Bridge",
    base64: "/9j/4AAQSkZJRgABAQEASABIAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIbGNtcwIQAABtbnRyUkdCIFhZWiAH4gADABQACQAOAB1hY3NwTVNGVAAAAABzYXdzY3RybAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLWhhbmRhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARUFNBwAAAAECAAAAAgAAAAAAAQAAAAAAAQAAAAAAAgAAAAYAAAAOAAAAaGVkcwAAAAsAAAAYaGVkc2NsbXMAAAABAAAAAmhlZHNtbG8AAAABAAAACHVzYmAAAAAJAAAAIHRleHQAAAAAQ29weXJpZ2h0IChjKSAyMDAwLCAyMDAxIFNhcmdlbnQgVGVjaG5vbG9naWVzLCBJbmMuIEFsbCByaWdodHMgcmVzZXJ2ZWQuAEhZWiAAAAAAAAD21gABAAAAANMtWFlaIAAAAAAAAG+iAAA49QAAA5BYWVogAAAAAAAAYqAAAMs0AAAK2VhZWiAAAAAAAAAknwAAD4QAALbEY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKMAqACtALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gIDAgwCFAIdAicCOAJBAksCVAJdAmcCcQJ6Ao4ClAKlAqwCsgLIAssC3ALzAwMDLAMsA0ADRARBEUMARhBPQFAAUwBUgFVAVgBYAFqAXQBfgGIAZIBnAGiAakBsQG5AcEByQHRAdkB4QHpAfIB+gL/Al8CngK+At8DvwPYA/8EYQTMBQAF3AYIBoYHFgddB4QH/wgRCCsJOAqADrQP7BAAENgRZBKQEyQXpBjsGeQPpB44H6AgWCDQIZgiWCQ4Jdgn4CgQKQApkCqgLBAu8DBgM+A0ADUgNYA2YDdQPGB/wIKgg/COQJFgl4CbgKBAqgCwwL+gzADCgM8A1sDcgOKBDsFNAY8BlIGuAb8ByAHYAfQCBwIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8BzAHYAfQCBAIWghUCJAIoAkkCTQJdAmQCbAJxAn4CigKUAq8CsALHAtEC2gLcAvIDBQMIAxIDNAM/A0sDWgNjA3IDfgOGA5IDpAOuA80D4gPwA/0EBAQ3BFIEgATcBSgFuAY8BpAGzAcQB3AHzwgACCYJTgl4CjALMgu4DAgM+g1sDdgOBA6wD2gP1BA8EaASuBOAFdQXgBnwGqgc4B9QIEghsCNgJJAlYCXQJmAnUCewKOApACpQKtArUCyALUAtwC8gMFAwsDGAMzBAcEHwRLBEsEPgRQBFAEbgSkBLoEwgTYBPcFRAVhBXkFfwYABhUGJwYwBjoGQAZPBmAGbAZ+BpIGtgb8B0AHRwf1B/gIEQgrCUsJtQnACeoLBAuIC/wMGAx4DUANzBAAENgRpBKwEyQXYBoYHBgdvB8QIFQgfCMEJMgm4CiwKqgucDDoMogzaDXoN7g4YDhQOew6VDuQPkA/gEBQQkBHEEpATgBPcFRAVixYEFnAXcBf4GEwYrBmAGeAaMBqgG+wcUBxQHYgekB9wIBggYCFgIXgiACIgI0AkcCWgJvAnMCewKQAqMCswLMAtgC5AL0AwADBgMIAw4DRAMuA0ADUgNWA2cDcgN8A4YDlgOiA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBEEEYgRsBOIFcgWUBbYGFgY5BlQGagbrBzUHYgeAB8wICgj7CTMKegrIDD4MrA1QDfwO1g+UEHwRgBHyEhYTQBOME5gVABXSFpQXABeYGDAYuBmgGhgatBvAHIAc9B2UHrAfxCBoIYQioCNAJCAlECYgJxAn8CjYKjAq0CvwLEgswC3AL0gwIDGgMsAzkDSwNbA3oDigOeA6sDywPiA/gEAQQLBCoEUgSYBNoFBAVcBaAF3AYEBhMGKAZIBnQGjgakBt4HBgchB10HiAeaB94IAAhSCJgIsAkSCTgJcAmUCaQJ1AnwCgYKGApYCpAKrAsMC0gLbAwADAgMMAxIDNwNGA1oDbQN7A4UDkgOhA6sDtgPLBDkETwRiBHYEkwTTBPAFCwVKBVwFdwWGBeAGHwYlBjsGRgZVBmQGcgahBqoGtgblBwQHJAczB08HggeyB9oICghFCHoI3AkUCUgJXgmgCbgJ8AocCjgKWgqECrgLDguRC8AMOAybDOwNUA1kDbAN7A4SDkgOXw6gDswPcBAGEEwQhBH4ElATaBUEFeoWUBcAGHAYrBmUGeQamBrcG9AdEB5YHxAgOCDoIigjMCPgJcgmcCggKlgrWDB4MWQzNDPgNUA10DbwN+A4iDmIOpA8gD4gQBBBoEXASNBOME/wVBBX4FvAYyBnYGvgc4B4QH3wgFCHoI2QklCWAJogomCpwK4gxQDHgM3A0UDWwNsA3oDiQOag6gDygPuhAIEQwRJBKQE5QV/Ba4GMwZ5Br8HOAeEB98IBQiECM0JHAloCbIKJAqbCuIMUAx4DNwNFQ1sDbAN6A4kDmoOoA8oD7oQCBEMEiQSkBOYFfwWuBjMGeQa/BzgHhAffCAUIhAjNCSEMhA2KDZIOjA+mEFgQ4BGYE6gUOBTYFZgWuBdoF/AYiBjkGYwZ6BqAGqwarBrkGvgbCBuoG9gcDBw8HJwdHB4MHkgelB8YH3Af8CAQIEgg2CDgIQQhHCHoIgwiRCLAI0gjvCToJVAlaCWQJbwmyCcwJ2wn0CgMKFAoqCjoKWgqbCqgKsgq6CsYK8gsGDCIMYgyKDMQNBA0wDUUNYA12DggOJA5QDmYOcw6dDswPChAYEEwQcBDwEYARuBIsExwT2BRQFQwVXBXoFgQWYBbwGAwYRBiEGNQZIBlQGbAadBqoGvgbCBvQHDQcZBz4HRAdXB5kHpQfZCBkIYAhtCJgI6QkMCToJaAmACZwKKApyCqIK1gt6DGAMcw04DWwN0g40DowOvw9jEIgQ4hLyE/gVDhYGFwoXThfaGAcYfBnzGo8bHBveHAYcCx1kHpcfzCAaIYsi0iQuJl0ngigNKQ0q5iwyLrsvbDAqMTwxvDPcNVA1xDcgOBQ5gDpsO6Q8RDycPSw+SD+EQChCRES0RrhK+Ey4TvhREFLgVuhYEFsoXbBgAGLwZsBoMGnQbYhyCHLwdZx5+HwQfziAGIP4hxiLYJDAmSCdIKKopZiuCLcAvYDA0MWAx4DIIMoQysjOKM+Q0NDToNf43JDkMOe47PDy8PoJAQkMCRkJMAlBCVMJcgmLiaEKggrSCwULlQvqDAcMGwxuDJ0M5g0cDWQNxQ4QDjUOhw7MDxsPNQ+MEBcQbhC8EdASVBOmFFgVaheSGN4Z2hqEGyQcRB1aHscgIiH4IqQleCakKLQqTCwoLjQwaDHIM1g3ADgQOdA7KDwMPVRAhEJwRvBL4E9AUyBXIFrwYdBnsGrAcAh1yHwQhSiNoJgAq6Cz4MBAyWDY0ON5AEkHcSd5N2E9gVDRZQF2QYEBl/GjYbMBx7HcEflCDiI7Yl8Ch2KsYvgDTwN6NAf0RzSg9PV1DkViNYPFlOWvJeyWOOZu9nlGkEaqxu9nMMc6x4XHv4g2yHcIu8m0yhOKoMtNzCsNlM55DzCP0tA6kQSRdJMcE5xUHhWj1v0YfJniGsoby9zOHRMewp/CIUojDCSiJaMo3CtVLvQzhDPsNeE6bDxQP2JCykU2Sm5MUU8lV8lfyWMJpVo4mmdb4Nz9HXte9yDSItMl5ic86IUp/iuMLJgssy4w8C0y8vVztXe4N/04vLnw+n07gQJBaQGFwc7B8UIMQl6CcsKrAu4DHkNCA4iDvsQiRKEFDsWOhpIHLkfxyMeJ4sozSvmMP81CDcuOoE/UUIiR/ZNJVFSV0pdn2QeaWptL3IidwF764FihS2LVJNRm4yjxavbtfG+68kIzU7X+eM76z/zBv9LBCcHdQfDCFIJewn/CykL2gy/DTsOaA+QEMkS1hTqFo8Z3hpwG30cxh2fHvofSiEyIn4jfSQrJicn4yisKiwrLCu8LDAscCzAprovyDA7MWoyZzNVM5g0LDVgNfQ29Df0ODo5vjrQOz883D2aPno/ZkBoQSJCfENiRCpFWkapS2tNWk9eULBSnlWIVp1XjFg0WhBbaF7wYjBkUGeYaNhrKHCgc7R3eHr8g+CKOJcMnaCjUq8YxLzXSOiQ/N0EnQf/CDwJMAp9C1MMtg1ZDfgOzA/zEVYVFRcwGSEbHB22H8MifiYHKQUs7DG2Ndg75kFASf1Mv1T4V+tlP2qxdHl8oIAYtPm+Gkj7f9vfr/sQI1BbMHNAfwCJMJ4Ar2C+sM2g15Dh0P1BE6E6oVWxesGaAbHBzMHeIfoiI8JLsmMylGKcIs0jEyNTM4dD8oRwNN/lYqXyRpoXY4geiXj6QJt+7b9e/c8ePy5frH/fUE+wdOCFwI/Qk3CqAL7gyhDW0OAQ+0ESIT4BWhF64ZlBrgG5Ic+B6iH7chxCOqJPwpwS3+MXo32D2kSNRR1lqUX25o9nSsfKW8rMIAzQzT09/h6c/z+/68BJ4HEwj7CVkKeAuCDKQNRA6SD+MQvBP7FV0XUBp2HMkfhSNqKHksfDCXN3A9/UW4UmBbJWOdZfRn2WqKb/N0wHrXgv+LSpBOlkym8LzRxsrJ0s3T0tbb3uDf4uPp7PP09/n7/P/+AQMEBQYICQoLCg0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/w==",
  }
];
