import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.join(process.cwd(),'src/data/transit/gauteng/unified-dev');
const qa=JSON.parse(fs.readFileSync(path.join(root,'reports','phase2c-qa.json'),'utf8'));
const rt=JSON.parse(fs.readFileSync(path.join(root,'runtime.json'),'utf8'));
const scenarios=JSON.parse(fs.readFileSync(path.join(root,'reports','phase2c-location-matrix.json'),'utf8'));
assert.equal(qa.errors.length,0);assert.equal(rt.phase2c.verifiedPassengerEdges,0);
assert.equal(qa.summary.officialHarambeeOperatorRouteLinksVerified,0);
assert.equal(qa.summary.verifiedPrasaStoppingPatterns,0);
assert(qa.summary.joburgRailLineShapes>0,'Missing downloaded Johannesburg PRASA railway line data');
assert.equal(qa.summary.ekurhuleniRailLineShapes,162,'Phase 2A source changed: inspect/revalidate before trusting prior counts');
assert.equal(qa.summary.ekurhuleniStations.stations,79);
assert.equal(qa.summary.johannesburgStations.stations,173);
assert(qa.summary.pairedGmsRouteStopLayers>=0&&qa.summary.pairedGmsRouteStopLayers<=7);
assert.equal(scenarios.zeroPassengerEdges,true);
for(const row of scenarios.scenarios)assert.equal(row.passengerEdges,0);
console.log('PASS: Phase 2C real GIS inputs: '+JSON.stringify(qa.summary));
console.log('PASS: '+scenarios.scenarios.length+' actual-data geographic examples, zero passenger edges.');
console.log('Report: '+path.join(root,'reports','phase2c-location-matrix.html'));
