import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const dir=path.join(process.cwd(),'src/data/transit/gauteng/unified-dev');
const read=(...p)=>JSON.parse(fs.readFileSync(path.join(dir,...p),'utf8'));
const runtime=read('runtime.json'),phase=read('reports','phase2c-gis-evidence.json'),qa=read('reports','phase2d-qa.json'),matrix=read('reports','phase2d-location-matrix.json');
const indexPath=path.join(dir,'phase2d-evidence.json'),index=read('phase2d-evidence.json');
assert.equal(runtime.internalOnly,true);assert.equal(phase.internalOnly,true);assert.equal(index.internalOnly,true);
assert.equal(index.sourceRightsCleared,false);assert.equal(index.passengerRoutingEnabled,false);
assert.equal(index.passengerEdges,0);assert.equal(index.boardingEdges,0);assert.equal(index.transferEdges,0);
assert.equal(index.routeShapes.length,runtime.geometryRoutes.length+phase.gmsGroups.reduce((s,g)=>s+g.routes.length,0));
assert.equal(index.railTrackShapes.length,phase.summary.joburgRailLineShapes+phase.summary.ekurhuleniRailLineShapes);
assert.equal(index.railStations.length,phase.summary.ekurhuleniStations.stations+phase.summary.johannesburgStations.stations);
assert.equal(index.routeShapes.filter(r=>r.operatorId==='ekurhuleni-gms-unassigned').length,phase.summary.GmsRouteFeatures);
assert.equal(index.routeShapes.every(r=>r.passengerRoutingEnabled===false),true);
assert.equal(index.routeShapes.filter(r=>r.operatorId==='ekurhuleni-gms-unassigned').every(r=>r.operatorAssignmentVerified===false),true);
assert.equal(qa.summary.anchoredRouteChecks,qa.summary.anchoredRouteChecksPassed);
assert.equal(qa.errors.length,0);assert.ok(matrix.rows.length>=8);
assert.equal(matrix.rows.filter(r=>r.scenarioType==='published-station-membership').every(r=>r.gautrainServiceMembership.length>0),true);
assert.equal(matrix.rows.every(r=>r.fare===null&&r.etaMinutes===null&&r.passengerRoutingEnabled===false),true);
assert.equal(qa.sourceIndexSha256,crypto.createHash('sha256').update(fs.readFileSync(indexPath)).digest('hex'));
console.log('PASS: Phase 2D actual-snapshot cross-checks:',JSON.stringify(qa.summary));
console.log('PASS: no inferred operating services, boarding, transfers, directions, fares or ETA.');
